export enum IndexButton {
    BEHAVIOR = 'CONTINUE TO BEHAVIOR',
    CONTEXT = 'CONTINUE TO CONTEXT',
    DEGREE = 'CONTINUE TO DEGREE',
    EMPLOYABILITY = 'CONTINUE TO EMPLOYABILITY',
    NOTES = 'CONTINUE TO NOTES',
    REVIEW = 'REVIEW COMPETENCY',
    SUBMIT = 'SUBMIT COMPETENCY'
}
