export enum IndexButton {
    BEHAVIOR = 'CONTINUE TO BEHAVIOR',
    CONTEXT = 'CONTINUE TO CONTEXT',
    TECHNOLOGY = 'CONTINUE TO TECHNOLOGY',
    DOCUMENTATION = 'CONTINUE TO DOCUMENTATION',
    DEGREE = 'CONTINUE TO DEGREE',
    RUBRIC = 'CONTINUE TO RUBRIC',
    EMPLOYABILITY = 'CONTINUE TO EMPLOYABILITY',
    NOTES = 'CONTINUE TO NOTES',
    REVIEW = 'REVIEW COMPETENCY',
    SUBMIT = 'SUBMIT COMPETENCY'
}
