version: 2.1

orbs:
  cyber4all: cyber4all/orb@2.0.11

workflows:
  ci:
    jobs:
      - cyber4all/lint
    
  continuous-delivery:
    when: 
      equal: [ staging, << pipeline.git.branch >> ]
    jobs:
      - cyber4all/s3:
          context: [AWS]
          name: deploy-staging
          bucket: "competency-client-staging"
          role-arn: S3_STAGING_OIDC_ROLE

  continuous-deployment:
    when:
      equal: [ releases, << pipeline.git.branch >> ]
    jobs:
      - cyber4all/release:
          context: [Github]
          tag: "$(jq -r '.version' package.json)"
        
      - cyber4all/s3:
          context: [AWS]
          requires: [cyber4all/release]
          name: deploy-production
          bucket: "cyber-competencies"
